# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '38 6 * * 6'

  jobs:
    clang-tidy:
      name: clang-tidy
  runs-on: ubuntu-latest
  steps:
    - name: clang-tidy check
      uses: smay1613/clang-tidy-action@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
